### ISSUE TITLE
Identify the connector

### ISSUE THREAD

**Issue by Ingramz** [Ingramz/ecl110#1]
Based on https://www.youtube.com/watch?v=icmg9PiaHfs&t=5 and measured board dimensions (connectable part width 1.25<13mm), my guess is that the card edge type connector is [Wieland DST(LF)85](https://eshop.wieland-electric.com/categorie/en/pcb-terminals--wiecon-edge-connectors-1000008692#filter=eyIxMjMiOlsiNTc5NiJdLCIxMzIiOlsiNzQyNCJdfQ%3D%3D)

The minimum order quantity is 50 and the price is not shown (expensive), but I will try getting one through local reseller as a sample.

**Comment by Sjoedin** [comment]
Hi,
What's the current status, have you tried the connector?

**Comment by Ingramz** [comment]
@Sjoedin unfortunately no, the local reseller did not reply to me.

**Comment by Ingramz** [comment]
I will try writing to Wieland directly and ask if I can get one from them instead, also ask around whether any my acquaintances knows someone from the reseller - maybe they take someone with previous business relations more seriously.

If you have interest, you can always try asking your local resellers.

**Comment by Sjoedin** [comment]
Do you know the exact art.no.?

**Comment by Ingramz** [comment]
It should be Art.No. 25.002.0453.0, however Art.No. 25.003.0453.0 is physically the same connector with OB designation (but with Wieland branding removed). Either one will do, if they happen to have any of them readily available.

The DSTLF85 connectors look like they have some sort of wings for better alignment with the PCB, but there are no such wings on the video so I would guess it is the regular DST85.

**Comment by Sjoedin** [comment]
Have you cheched with Danfoss if they could supply a "spare part"..?

**Comment by Ingramz** [comment]
No, I haven't. Estonian support has been little help and it seems everything I ask, they ask someone from Denmark, which takes considerable amount of time for me to get a reply. Sometimes they "forget" to even answer.

They don't disclose the e-mail addresses of the Danish employees, which makes it hard for me to establish communication with those people directly.

But again, if you are willing to try that route and it works for you, then it might turn out to be a good way of obtaining such spares. I don't simply have much faith in my local Danfoss branch.

**Comment by Ingramz** [comment]
Wieland has not responed in the 5 days, neither I have found someone who might know somone from local reseller so that I could get an answer.

I've been searching for products based on those two art. no-s from google and places which sell them have outrageous surcharges, which makes it actually cheaper to just buy 50 from Wieland if they ever decide to respond.

I will stick to wires soldered directly on pads for now.

**Comment by Sjoedin** [comment]
I sent a mail to Danfoss 5-6 Days ago, no replies yet...

**Comment by aviborg** [comment]
I found them at https://www.onlinecomponents.com/wieland-electric-2500304530.html?p=11316631 for $4.04/unit but they require a minimum order of $200 if you're located outside the US. So buy 50 and sell the rest on Ebay? I would definitely pay $10 myself if it was on Ebay. Currently I have crocodile clips connected, but it's a very flimsy solution. So what do you say if I make an order? I have a business case of at least 2 sold units as I see it. :)

**Comment by Ingramz** [comment]
@aviborg absolutely :) I don't mind if anyone did that especially when willing to deal with sales through ebay, however I am pointing out that you are knowingly taking a risk that this might not be the correct connector. The Wieland one is by far the best candidate that I have found from the internet, based on the video/images and technical drawings. Even if it fits, I would first test the continuity between the pads to verify that it is not causing any short circuits if it happens that one pin touches two pads.

I think I saw some places which had a smaller minimum order than the one you found for $200, but I could be easily mistaken as I checked it a week ago, which I have now long forgotten. If Wieland or your local reseller takes you seriously, they might offer you a better price for 50 than any of the retailers.

**Comment by Sjoedin** [comment]
Got a reply from Danfoss, apparently they don’t have it as a ”spare part”.
However, they indicated that possibly they could take one from a ”complete kit”.
I asked for a price but haven’t received an answer yet.

**Comment by Ingramz** [comment]
Interesting. Thanks for letting us know.

It would be interesting to know how much does a DLG cost. There is one on amazon.de for 219,99€, but for something this simple, it does not seem a good value to me. Maybe at fifth/tenth of the cost it would make sense.

Either way, if anyone had it (and the Danfoss Link CC) even for a few days, it would help solving this issue and #2.

**Comment by aviborg** [comment]
I just placed an order for 59 connectors at onlinecomponents.com.
I'll try to sell the extra 58 on ebay :)
If anyone need one let me know!

**Comment by Ingramz** [comment]
@aviborg 👍 Let us know once you have received and tried them. I would be interested in 2.

**Comment by Sjoedin** [comment]
FYI, I received a shipment from Danfoss but unfortunately it wasn’t the right connector... 😕

**Comment by aviborg** [comment]
Interesting that they do not know themselves what kind of connector it is. Anyway I'm expecting a shipment to arrive on 11 january. Let's hope the Wieland connector fits, otherwise it is $250 wasted, I'll keep you updated!

**Comment by aviborg** [comment]
Got the connectors today and it's a perfect fit!
@Ingramz @Sjoedin send me a PM with your addresses and I will ship connectors to you!

I'm selling the rest on ebay, you can find some pics there: https://www.ebay.co.uk/itm/173089634501

**Comment by Sjoedin** [comment]
Great!
Just one issue, how so I send a PM..? 😀

**Comment by aviborg** [comment]
Seems there is no functionality for that on github, oops!

@Sjoedin Send me your address to andreas (dot) viborg (a) gmail (dot) com

**Comment by Ingramz** [comment]
The connectors sent by @aviborg arrived to post office 2 days ago. I now had the chance to make cables and clean up soldered wires from the board.

The fit is indeed extremely tight and the pads are perfectly aligned with contacts. There is no doubt that this is the connector. Case closed!

**Comment by petergp** [comment]
@aviborg do you still have any of the connectors left?

**Comment by aviborg** [comment]
@petergp 
At time of writing I got a few.
I have a fork of this repo where I will update the status of remaining connectors and payment link to paypal:
https://github.com/aviborg/ecl110

**Comment by JohNan** [comment]
@aviborg I can't see any status on how many connectors you have left in the repo you linked to. So do you have any connectors left? Im located in Sweden :)

**Comment by aviborg** [comment]
I have connectors atm.

Here are my selling page https://www.tradera.com/profile/items/309378/aviborg

**Comment by JohNan** [comment]
> I have connectors atm.
> 
> Here are my selling page https://www.tradera.com/profile/items/309378/aviborg

Thank you! I just got placed an order!

**Comment by alfs** [comment]
Since aviborg has now sold out all connectors, an alternative is to 3D-print from Wieland CAD files.

1. Get the STP file from https://eshop.wieland-electric.com/download/25.003.0453.0/DC0017610.STP
2. Open in Autocad Fusion, delete the orange phillips screws and add holes for wires
3. 3D print 
4. Glue metal sheets on the connector tounges, connect wires or add screw blocks, and it should be it

If the direct link to the cad file fails, it was found at the download section, CAD bilddaten, at 
 https://eshop.wieland-electric.com/products/de/leiterplattendirektsteckklemme-dst85--4-ob/25.003.0453.0?vendorProductId=25.003.0453.0&navigate=0#downloads
