### ISSUE TITLE
Connection question

### ISSUE THREAD

**Issue by GruffyPuffy** [Ingramz/ecl110#5]
Hi,

Thanks for the work with this. Recently moved to a house where I have an ECL 110 and I got interested in this. Got myself an RS485 usb dongle on order. However, I hesitate a little with connecting this straight into a Pi when I have GND connected. Heard of some possible issues with heating systems and connecting GND to a power connected device. Any thoughts on this for ECL 110? Can I just connect the USB dongle into the Pi, wire up A/B and GND from it without "letting out the magic smoke" from my ECL110?

**Comment by GruffyPuffy** [comment]
I will answer myself...yes it works. No trouble in hooking it up.

**Comment by Ingramz** [comment]
Marking this as solved, apologies for not noticing it any sooner, that should have been an easy question to answer.
